[package]
name = "iterfam"
version = "0.1.0"
authors = ["Nate Wilcox <nathan+dev@electriccoin.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
test-case = "1.2.0"
